"""Catalog of human bones with metadata."""

BONES = [
    # Skull — cranial bones
    {
        "id": "frontal",
        "name": "Frontal bone",
        "region": "skull",
        "sub_region": "cranial",
        "wikipedia": "Frontal bone",
        "description": "Forms the forehead and the roof of the eye sockets.",
    },
    {
        "id": "parietal",
        "name": "Parietal bone",
        "region": "skull",
        "sub_region": "cranial",
        "wikipedia": "Parietal bone",
        "description": "Paired bones forming the sides and roof of the skull.",
    },
    {
        "id": "temporal",
        "name": "Temporal bone",
        "region": "skull",
        "sub_region": "cranial",
        "wikipedia": "Temporal bone",
        "description": "Paired bones at the sides and base of the skull, housing the ear structures.",
    },
    {
        "id": "occipital",
        "name": "Occipital bone",
        "region": "skull",
        "sub_region": "cranial",
        "wikipedia": "Occipital bone",
        "description": "Forms the back and base of the skull, contains the foramen magnum.",
    },
    {
        "id": "sphenoid",
        "name": "Sphenoid bone",
        "region": "skull",
        "sub_region": "cranial",
        "wikipedia": "Sphenoid bone",
        "description": "Butterfly-shaped bone at the base of the skull.",
    },
    {
        "id": "ethmoid",
        "name": "Ethmoid bone",
        "region": "skull",
        "sub_region": "cranial",
        "wikipedia": "Ethmoid bone",
        "description": "Delicate bone between the eye sockets, forms part of the nasal cavity.",
    },
    # Skull — facial bones
    {
        "id": "mandible",
        "name": "Mandible",
        "region": "skull",
        "sub_region": "facial",
        "wikipedia": "Mandible",
        "description": "The lower jawbone, the largest and strongest bone of the face.",
    },
    {
        "id": "maxilla",
        "name": "Maxilla",
        "region": "skull",
        "sub_region": "facial",
        "wikipedia": "Maxilla",
        "description": "Paired bones forming the upper jaw and central part of the face.",
    },
    {
        "id": "zygomatic",
        "name": "Zygomatic bone",
        "region": "skull",
        "sub_region": "facial",
        "wikipedia": "Zygomatic bone",
        "description": "The cheekbone.",
    },
    {
        "id": "nasal",
        "name": "Nasal bone",
        "region": "skull",
        "sub_region": "facial",
        "wikipedia": "Nasal bone",
        "description": "Paired bones forming the bridge of the nose.",
    },
    {
        "id": "lacrimal",
        "name": "Lacrimal bone",
        "region": "skull",
        "sub_region": "facial",
        "wikipedia": "Lacrimal bone",
        "description": "Smallest bones of the face, at the inner wall of each eye socket.",
    },
    {
        "id": "palatine",
        "name": "Palatine bone",
        "region": "skull",
        "sub_region": "facial",
        "wikipedia": "Palatine bone",
        "description": "Paired L-shaped bones forming part of the hard palate and nasal cavity.",
    },
    {
        "id": "inferior-nasal-concha",
        "name": "Inferior nasal concha",
        "region": "skull",
        "sub_region": "facial",
        "wikipedia": "Inferior nasal concha",
        "description": "Scroll-shaped bones in the nasal cavity that filter and humidify air.",
    },
    {
        "id": "vomer",
        "name": "Vomer",
        "region": "skull",
        "sub_region": "facial",
        "wikipedia": "Vomer",
        "description": "Thin flat bone forming part of the nasal septum.",
    },
    # Ear ossicles
    {
        "id": "malleus",
        "name": "Malleus",
        "region": "skull",
        "sub_region": "ear ossicles",
        "wikipedia": "Malleus",
        "description": "The hammer-shaped bone, largest of the three ear ossicles.",
    },
    {
        "id": "incus",
        "name": "Incus",
        "region": "skull",
        "sub_region": "ear ossicles",
        "wikipedia": "Incus",
        "description": "The anvil-shaped middle ear bone.",
    },
    {
        "id": "stapes",
        "name": "Stapes",
        "region": "skull",
        "sub_region": "ear ossicles",
        "wikipedia": "Stapes",
        "description": "The stirrup-shaped bone, smallest bone in the human body.",
    },
    # Throat
    {
        "id": "hyoid",
        "name": "Hyoid bone",
        "region": "throat",
        "sub_region": None,
        "wikipedia": "Hyoid bone",
        "description": "U-shaped bone in the neck, the only bone not articulating with another bone.",
    },
    # Spine
    {
        "id": "atlas",
        "name": "Atlas",
        "region": "spine",
        "sub_region": "cervical",
        "wikipedia": "Atlas (anatomy)",
        "description": "First cervical vertebra (C1), supports the skull.",
    },
    {
        "id": "axis",
        "name": "Axis",
        "region": "spine",
        "sub_region": "cervical",
        "wikipedia": "Axis (anatomy)",
        "description": "Second cervical vertebra (C2), allows rotation of the head.",
    },
    {
        "id": "cervical-vertebrae",
        "name": "Cervical vertebrae",
        "region": "spine",
        "sub_region": "cervical",
        "wikipedia": "Cervical vertebrae",
        "description": "Seven vertebrae (C1-C7) forming the neck region of the spine.",
    },
    {
        "id": "thoracic-vertebrae",
        "name": "Thoracic vertebrae",
        "region": "spine",
        "sub_region": "thoracic",
        "wikipedia": "Thoracic vertebrae",
        "description": "Twelve vertebrae (T1-T12) articulating with the ribs.",
    },
    {
        "id": "lumbar-vertebrae",
        "name": "Lumbar vertebrae",
        "region": "spine",
        "sub_region": "lumbar",
        "wikipedia": "Lumbar vertebrae",
        "description": "Five large vertebrae (L1-L5) of the lower back.",
    },
    {
        "id": "sacrum",
        "name": "Sacrum",
        "region": "spine",
        "sub_region": "sacral",
        "wikipedia": "Sacrum",
        "description": "Triangular bone of five fused vertebrae at the base of the spine.",
    },
    {
        "id": "coccyx",
        "name": "Coccyx",
        "region": "spine",
        "sub_region": "sacral",
        "wikipedia": "Coccyx",
        "description": "The tailbone, three to five fused vertebrae at the bottom of the spine.",
    },
    # Thorax
    {
        "id": "sternum",
        "name": "Sternum",
        "region": "thorax",
        "sub_region": None,
        "wikipedia": "Sternum",
        "description": "The breastbone, a flat bone at the front of the chest.",
    },
    {
        "id": "manubrium",
        "name": "Manubrium",
        "region": "thorax",
        "sub_region": None,
        "wikipedia": "Manubrium",
        "description": "The broad upper part of the sternum.",
    },
    {
        "id": "xiphoid-process",
        "name": "Xiphoid process",
        "region": "thorax",
        "sub_region": None,
        "wikipedia": "Xiphoid process",
        "description": "Small cartilaginous extension at the lower end of the sternum.",
    },
    {
        "id": "rib",
        "name": "Rib",
        "region": "thorax",
        "sub_region": "ribs",
        "wikipedia": "Rib",
        "description": "Twelve pairs of curved bones forming the ribcage.",
    },
    # Shoulder
    {
        "id": "clavicle",
        "name": "Clavicle",
        "region": "upper limb",
        "sub_region": "shoulder",
        "wikipedia": "Clavicle",
        "description": "The collarbone, connecting the arm to the body.",
    },
    {
        "id": "scapula",
        "name": "Scapula",
        "region": "upper limb",
        "sub_region": "shoulder",
        "wikipedia": "Scapula",
        "description": "The shoulder blade, a flat triangular bone on the back.",
    },
    # Upper arm
    {
        "id": "humerus",
        "name": "Humerus",
        "region": "upper limb",
        "sub_region": "arm",
        "wikipedia": "Humerus",
        "description": "The long bone of the upper arm.",
    },
    # Forearm
    {
        "id": "radius",
        "name": "Radius",
        "region": "upper limb",
        "sub_region": "forearm",
        "wikipedia": "Radius (bone)",
        "description": "The shorter forearm bone on the thumb side.",
    },
    {
        "id": "ulna",
        "name": "Ulna",
        "region": "upper limb",
        "sub_region": "forearm",
        "wikipedia": "Ulna",
        "description": "The longer forearm bone on the little finger side.",
    },
    # Wrist (carpals)
    {
        "id": "scaphoid",
        "name": "Scaphoid bone",
        "region": "upper limb",
        "sub_region": "wrist",
        "wikipedia": "Scaphoid bone",
        "description": "Boat-shaped carpal bone, the most commonly fractured wrist bone.",
    },
    {
        "id": "lunate",
        "name": "Lunate bone",
        "region": "upper limb",
        "sub_region": "wrist",
        "wikipedia": "Lunate bone",
        "description": "Crescent-shaped carpal bone in the center of the wrist.",
    },
    {
        "id": "triquetral",
        "name": "Triquetral bone",
        "region": "upper limb",
        "sub_region": "wrist",
        "wikipedia": "Triquetral bone",
        "description": "Pyramid-shaped carpal bone on the inner side of the wrist.",
    },
    {
        "id": "pisiform",
        "name": "Pisiform bone",
        "region": "upper limb",
        "sub_region": "wrist",
        "wikipedia": "Pisiform bone",
        "description": "Small pea-shaped sesamoid bone in the wrist.",
    },
    {
        "id": "trapezium",
        "name": "Trapezium",
        "region": "upper limb",
        "sub_region": "wrist",
        "wikipedia": "Trapezium (bone)",
        "description": "Carpal bone at the base of the thumb.",
    },
    {
        "id": "trapezoid",
        "name": "Trapezoid bone",
        "region": "upper limb",
        "sub_region": "wrist",
        "wikipedia": "Trapezoid bone",
        "description": "The smallest carpal bone in the distal row.",
    },
    {
        "id": "capitate",
        "name": "Capitate bone",
        "region": "upper limb",
        "sub_region": "wrist",
        "wikipedia": "Capitate bone",
        "description": "The largest carpal bone, at the center of the wrist.",
    },
    {
        "id": "hamate",
        "name": "Hamate bone",
        "region": "upper limb",
        "sub_region": "wrist",
        "wikipedia": "Hamate bone",
        "description": "Wedge-shaped carpal bone with a hook-like process.",
    },
    # Hand
    {
        "id": "metacarpals",
        "name": "Metacarpal bones",
        "region": "upper limb",
        "sub_region": "hand",
        "wikipedia": "Metacarpal bones",
        "description": "Five bones forming the palm of the hand.",
    },
    {
        "id": "proximal-phalanx-hand",
        "name": "Proximal phalanx (hand)",
        "region": "upper limb",
        "sub_region": "hand",
        "wikipedia": "Proximal phalanx",
        "description": "The finger bone closest to the palm.",
    },
    {
        "id": "middle-phalanx-hand",
        "name": "Middle phalanx (hand)",
        "region": "upper limb",
        "sub_region": "hand",
        "wikipedia": "Middle phalanx",
        "description": "The middle finger bone (absent in the thumb).",
    },
    {
        "id": "distal-phalanx-hand",
        "name": "Distal phalanx (hand)",
        "region": "upper limb",
        "sub_region": "hand",
        "wikipedia": "Distal phalanx",
        "description": "The fingertip bone.",
    },
    # Pelvis
    {
        "id": "hip-bone",
        "name": "Hip bone",
        "region": "pelvis",
        "sub_region": None,
        "wikipedia": "Hip bone",
        "description": "Large irregular bone formed by the fusion of ilium, ischium, and pubis.",
    },
    {
        "id": "ilium",
        "name": "Ilium",
        "region": "pelvis",
        "sub_region": None,
        "wikipedia": "Ilium (bone)",
        "description": "The largest and most superior part of the hip bone.",
    },
    {
        "id": "ischium",
        "name": "Ischium",
        "region": "pelvis",
        "sub_region": None,
        "wikipedia": "Ischium",
        "description": "The lower back part of the hip bone, bears body weight when sitting.",
    },
    {
        "id": "pubis",
        "name": "Pubis",
        "region": "pelvis",
        "sub_region": None,
        "wikipedia": "Pubis (bone)",
        "description": "The front part of the hip bone.",
    },
    # Thigh
    {
        "id": "femur",
        "name": "Femur",
        "region": "lower limb",
        "sub_region": "thigh",
        "wikipedia": "Femur",
        "description": "The thighbone, longest and strongest bone in the body.",
    },
    # Knee
    {
        "id": "patella",
        "name": "Patella",
        "region": "lower limb",
        "sub_region": "knee",
        "wikipedia": "Patella",
        "description": "The kneecap, a thick circular-triangular sesamoid bone.",
    },
    # Lower leg
    {
        "id": "tibia",
        "name": "Tibia",
        "region": "lower limb",
        "sub_region": "leg",
        "wikipedia": "Tibia",
        "description": "The shinbone, larger of the two lower leg bones.",
    },
    {
        "id": "fibula",
        "name": "Fibula",
        "region": "lower limb",
        "sub_region": "leg",
        "wikipedia": "Fibula",
        "description": "The thinner bone on the outer side of the lower leg.",
    },
    # Ankle (tarsals)
    {
        "id": "calcaneus",
        "name": "Calcaneus",
        "region": "lower limb",
        "sub_region": "ankle",
        "wikipedia": "Calcaneus",
        "description": "The heel bone, largest bone in the foot.",
    },
    {
        "id": "talus",
        "name": "Talus",
        "region": "lower limb",
        "sub_region": "ankle",
        "wikipedia": "Talus bone",
        "description": "Sits between the tibia and calcaneus, forming the ankle joint.",
    },
    {
        "id": "navicular",
        "name": "Navicular bone",
        "region": "lower limb",
        "sub_region": "ankle",
        "wikipedia": "Navicular bone",
        "description": "Boat-shaped bone on the inner side of the foot.",
    },
    {
        "id": "cuboid",
        "name": "Cuboid bone",
        "region": "lower limb",
        "sub_region": "ankle",
        "wikipedia": "Cuboid bone",
        "description": "Cube-shaped bone on the outer side of the foot.",
    },
    {
        "id": "medial-cuneiform",
        "name": "Medial cuneiform bone",
        "region": "lower limb",
        "sub_region": "ankle",
        "wikipedia": "Medial cuneiform bone",
        "description": "The largest cuneiform, on the inner side of the foot.",
    },
    {
        "id": "intermediate-cuneiform",
        "name": "Intermediate cuneiform bone",
        "region": "lower limb",
        "sub_region": "ankle",
        "wikipedia": "Intermediate cuneiform bone",
        "description": "The smallest cuneiform, in the middle of the foot.",
    },
    {
        "id": "lateral-cuneiform",
        "name": "Lateral cuneiform bone",
        "region": "lower limb",
        "sub_region": "ankle",
        "wikipedia": "Lateral cuneiform bone",
        "description": "Wedge-shaped bone on the outer side of the foot.",
    },
    # Foot
    {
        "id": "metatarsals",
        "name": "Metatarsal bones",
        "region": "lower limb",
        "sub_region": "foot",
        "wikipedia": "Metatarsal bones",
        "description": "Five long bones in the middle of the foot.",
    },
    {
        "id": "proximal-phalanx-foot",
        "name": "Proximal phalanx (foot)",
        "region": "lower limb",
        "sub_region": "foot",
        "wikipedia": "Proximal phalanx",
        "description": "The toe bone closest to the foot.",
    },
    {
        "id": "middle-phalanx-foot",
        "name": "Middle phalanx (foot)",
        "region": "lower limb",
        "sub_region": "foot",
        "wikipedia": "Middle phalanx",
        "description": "The middle toe bone (absent in the big toe).",
    },
    {
        "id": "distal-phalanx-foot",
        "name": "Distal phalanx (foot)",
        "region": "lower limb",
        "sub_region": "foot",
        "wikipedia": "Distal phalanx",
        "description": "The tip of the toe.",
    },
]

BONES_BY_ID = {b["id"]: b for b in BONES}
REGIONS = sorted(set(b["region"] for b in BONES))
